name: Build & Release

on:
  push:
    tags:
      - 'v*.*.*'   # каждый новый тег = релиз

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare artifacts
        run: |
          mkdir release
          cp manifest.json main.js release/
          if [ -f styles.css ]; then cp styles.css release/; fi
          cd release && zip -r ../year-planner.zip .

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            year-planner.zip
            manifest.json
            main.js
            styles.css
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}