name: Build & Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write   # 👈 adding permissions for releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - run: |
          mkdir release
          cp manifest.json main.js release/
          if [ -f styles.css ]; then cp styles.css release/; fi
          cd release && zip -r ../year-planner.zip .
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            year-planner.zip
            manifest.json
            main.js
            styles.css
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
